# config/training/default.yaml
# Training settings
output_dir: "outputs"  # 出力ベースディレクトリ
max_epochs: 500       # 最大エポック数
batch_size: 40        # 1回の学習ステップで処理する画像パッチの数
num_workers: 5        # データローダーの並列数

# 損失関数の重み設定
reconstruction_weight: 4.0  # 再構成損失の重み
adversarial_weight: 0.5    # 敵対的損失の重み
use_image_loss: true       # 画像損失を使用するか
reconstruction_criterion: L1Loss  # 再構成損失の種類（L1損失）
adversarial_criterion: MSELoss  # 敵対的損失の種類（MSE損失）
learning_rate: 0.0004           # 基本学習率

# 勾配クリッピングの設定
use_gradient_clipping: true     # 勾配クリッピングを使用するか
gradient_clip_val: 0.5          # クリッピングの閾値

# Early Stopping設定
early_stopping: true           # Early Stoppingを使用するか
early_stopping_patience: 5    # 改善が見られないまま待機するエポック数

# ハードウェア設定
accelerator: "auto"  # 使用するアクセラレータ ("cpu", "gpu", "auto")
devices: 1          # 使用するデバイス数
precision: 32       # 演算精度（16, 32, または "bf16"）

# 学習の最適化設定
accumulate_grad_batches: 1    # 勾配を蓄積するバッチ数
deterministic: false          # 決定論的な動作にするか
log_every_n_steps: 10        # ログを出力するステップ間隔

# ログ
image_log_freq: 100
save_interval: 100           # モデルを保存する間隔