# config/training/default.yaml
# Training settings
output_dir: "outputs"
max_epochs: 500
batch_size: 40
num_workers: 4

# Optimization
reconstruction_weight: 4.0
adversarial_weight: 0.5
use_image_loss: true
reconstruction_criterion: L1Loss
adversarial_criterion: MSELoss
learning_rate: 0.0004

# Early stopping
early_stopping: true
early_stopping_patience: 20

# Hardware settings
accelerator: "auto"  # "cpu", "gpu", "auto"
devices: 1
precision: 32       # 16, 32, or "bf16"

# Training optimizations
accumulate_grad_batches: 1
gradient_clip_val: 0.5
deterministic: false
log_every_n_steps: 10

# Logging
save_interval: 100