# 基本設定の継承
defaults:
  - model: default            # モデル設定
  - training: default        # トレーニング設定
  - optimizer: default       # オプティマイザー設定
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

# Hydra設定
hydra:
  output_subdir: null
  run:
    dir: .

# パスの設定
paths:
  checkpoint: "outputs/checkpoints/last.ckpt"
  input_dir: "test_dataset/PlatinumChan_x0.5_gen/input"
  mask_dir: "test_dataset/PlatinumChan_x0.5_gen/mask"
  output_dir: "test_dataset/PlatinumChan_x0.5_gen/output"
  additional_channels:
    point_vector:
      path: "test_dataset/PlatinumChan_x0.5_gen/tracking"
      depth: 3
  
# 推論の設定
inference:
  use_gpu: true
  debug_mode: false

# データ設定
data:
  dir_pre: ${paths.input_dir}    
  dir_mask: ${paths.mask_dir}    
  dir_post: null                 
  patch_size: 80                 
  additional_channels: {}
  augmentation_factor: 1
